version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imersao17
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3366
    volumes:
      - .docker/mysql:/var/lib/mysql
